export const shadcnComponentGroups = [
  {
    name: "Base",
    components: [
      "accordion",
      "alert",
      "alert-dialog",
      "aspect-ratio",
      "avatar",
      "badge",
      "button",
      "button-group",
      "card",
      "collapsible",
      "separator",
    ],
  },
  {
    name: "Forms",
    components: [
      "calendar",
      "checkbox",
      "combobox",
      "field",
      "form",
      "input",
      "input-group",
      "input-otp",
      "label",
      "native-select",
      "radio-group",
      "select",
      "slider",
      "switch",
      "textarea",
      "toggle",
      "toggle-group",
    ],
  },
  {
    name: "Navigation",
    components: [
      "breadcrumb",
      "command",
      "menubar",
      "navigation-menu",
      "pagination",
      "sidebar",
      "tabs",
    ],
  },
  {
    name: "Overlays",
    components: [
      "context-menu",
      "dialog",
      "drawer",
      "dropdown-menu",
      "hover-card",
      "popover",
      "sheet",
      "tooltip",
    ],
  },
  {
    name: "Data",
    components: [
      "carousel",
      "chart",
      "item",
      "resizable",
      "scroll-area",
      "table",
    ],
  },
  {
    name: "Feedback",
    components: [
      "empty",
      "kbd",
      "progress",
      "skeleton",
      "sonner",
      "spinner",
    ],
  },
  {
    name: "Utilities",
    components: ["direction"],
  },
] as const

export const starterComponentNames = [
  "accordion",
  "alert",
  "alert-dialog",
  "aspect-ratio",
  "avatar",
  "badge",
  "breadcrumb",
  "button",
  "button-group",
  "calendar",
  "card",
  "carousel",
  "chart",
  "checkbox",
  "collapsible",
  "combobox",
  "command",
  "context-menu",
  "dialog",
  "direction",
  "drawer",
  "dropdown-menu",
  "empty",
  "field",
  "form",
  "hover-card",
  "input",
  "input-group",
  "input-otp",
  "item",
  "kbd",
  "label",
  "menubar",
  "native-select",
  "navigation-menu",
  "pagination",
  "popover",
  "progress",
  "radio-group",
  "resizable",
  "scroll-area",
  "select",
  "separator",
  "sheet",
  "sidebar",
  "slider",
  "skeleton",
  "sonner",
  "spinner",
  "switch",
  "table",
  "tabs",
  "textarea",
  "tooltip",
  "toggle",
  "toggle-group",
] as const
